# Proposal

## Research topic

Education is important. From the society’s perspective, more people attending higher education can create a better workforce that boosts the economy and more educated citizens that together create a better society. From the individual’s perspective, higher education means more opportunity and more knowledge for personal growth. However, not all family can afford the tuition needed, and many may lose the chance due to poverty. In order to support those families, state organization such as the Higher Education Service Corporation was created to centrally administer student financial aid programs, and the Tuition Assistance Program (TAP) is one of them.

So, the question was proposed - `How does the Tuition Assistance Program (TAP) distribute its financial aid?` In other words, we want to investigate the decision making process of the TAP program to see the important features that may affect the disposal of the financial aid and dollar amounts being provided. We also would like to check `whether there will be changes in distribution or total financial aid amount after the COVID pandemic`, specifically in the year 2019 and 2020, as compared to previous years.

## Data availability

The data is from NY Open Data, provided by the New York State Higher Education Services Corporation.

The original source of the data can be found here: 
[Tuition Assistance Program Dataset](https://data.ny.gov/Education/Tuition-Assistance-Program-TAP-Recipients-Dollars-/2t78-bs45)

We eventually choose this dataset because it focuses on the Tuition Assistance Program (TAP), which is New York's largest student financial aid grant program that helps eligible in-state residents pay tuition at approved schools in New York State. The datasets therefore can be representative to investigate the overall distribution of financial aid funds in New York State.  

This dataset provides insights about TAP award recipients by education level, sector of institution, age, income, and some other characteristics each year beginning from 2000. This dataset will be updated every November.

Information contained in this dataset was extracted from the systems that process student application and school certification data as described above and collated by academic year, TAP College Code, school sector, and Federal School Code to facilitate matching with US Department of Education administered loan and grant program data. It is updated in November of each year, coinciding with the publication of the HESC Annual Report. 

In terms of the quality of the data, the information for the most recent year is estimated, and may be adjusted several years after an academic year has passed. Other than the accuracy, the data is comprehensive and does not contain missing values.

The data is available in five formats: CSV, TSV, RDF, XML, RSS. We decided to use the CSV format, and we will directly download the data from the website where the data is updated annually. 

For additional information and questions, we can contact the database owner directly through the website. 


